### ISSUE TITLE
Cannot run headlessly

### ISSUE THREAD

**Issue by psibre** [EllaVator/EllaVator#95]
Trying to run in a headless environment causes a headless exception:

```
$ ./gradlew run
Starting a new Gradle Daemon for this build (subsequent builds will be faster).
:sphinx4:sphinx4-data:compileJava UP-TO-DATE
:sphinx4:sphinx4-data:compileGroovy UP-TO-DATE
:sphinx4:sphinx4-data:processResources UP-TO-DATE
:sphinx4:sphinx4-data:classes UP-TO-DATE
:sphinx4:sphinx4-data:jar UP-TO-DATE
:sphinx4:sphinx4-core:compileJava UP-TO-DATE
:sphinx4:sphinx4-core:compileGroovy UP-TO-DATE
:sphinx4:sphinx4-core:processResources UP-TO-DATE
:sphinx4:sphinx4-core:classes UP-TO-DATE
:sphinx4:sphinx4-core:jar UP-TO-DATE
:compileJava UP-TO-DATE
:compileGroovy UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:run
java.lang.UnsatisfiedLinkError: no rxtxSerial in java.library.path thrown while loading gnu.io.RXTXCommDriver
no rxtxSerial in java.library.path
[OpenDial] INFO: Module ModuleElla successfully attached 
[OpenDial] INFO: Module AudioModule successfully attached 
[OpenDial] INFO: Acoustic model: resource:/edu/cmu/sphinx/models/en-us/en-us 
[OpenDial] INFO: Dictionary: resource:/grammar_en/ella_en.dict 
[OpenDial] INFO: Recognition grammar: resource:/grammar_en/compact_gram.gram 
[OpenDial] WARNING: could not start module opendial.gui.GUIFrame: java.awt.HeadlessException 
java.awt.HeadlessException
    at java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:204)
    at java.awt.Window.<init>(Window.java:536)
    at java.awt.Frame.<init>(Frame.java:420)
    at java.awt.Frame.<init>(Frame.java:385)
    at javax.swing.JFrame.<init>(JFrame.java:189)
    at opendial.gui.GUIFrame.start(GUIFrame.java:111)
    at opendial.DialogueSystem.startSystem(DialogueSystem.java:149)
    at OpenDialDemo.main(OpenDialDemo.java:44)
[OpenDial] WARNING: could not start module ModuleElla: java.awt.HeadlessException 
java.awt.HeadlessException
    at java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:204)
    at java.awt.Window.<init>(Window.java:536)
    at java.awt.Frame.<init>(Frame.java:420)
    at java.awt.Frame.<init>(Frame.java:385)
    at javax.swing.JFrame.<init>(JFrame.java:189)
    at ModuleElla.start(ModuleElla.java:56)
    at opendial.DialogueSystem.startSystem(DialogueSystem.java:149)
    at OpenDialDemo.main(OpenDialDemo.java:44)
> Building 93% > :run
```

It's not clear if the system itself is functional at that point (and only the GUI monitor is failing), or if everything hangs in a broken state...

**Comment by psibre** [comment]
This may or may not be related to plison/opendial#13.
